services:
    nginx:
        container_name: eva-nginx
        image: nginx:${NGINX_VERSION:-1.29.1}
        ports:
            - "2137:80"
        depends_on:
            - php
        volumes:
            - '.docker/nginx/eva.conf:/etc/nginx/conf.d/default.conf'
            - '.:/var/www/eva:ro'
    php:
        container_name: eva-php
        image: bmxmale/eva-php:8.4-fpm
        build: '.docker/php'
        depends_on:
            - db
        volumes:
            - '.:/var/www/eva'
        environment:
            - "DATABASE_URL=mysql://${MYSQL_USER:-eva}:${MYSQL_PASSWORD:-eva}@db:3306/${MYSQL_DATABASE:-eva}?sslmode=disable&charset=utf8mb4&serverVersion=10.11.0-mariadb"
    db:
        container_name: eva-mysql
        image: mariadb:10.11
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-eva}
            MYSQL_USER: ${MYSQL_USER:-eva}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-eva}
        volumes:
            - '.docker/mysql/test_db.sql:/docker-entrypoint-initdb.d/init.sql:ro'
            - db_data:/var/lib/mysql

volumes:
    db_data:
